# Pytorch primeros pasos

In [2]:
import torch

In [9]:
# Construir un tensor con valores en 0
x = torch.empty(4, 5, 2)
x

tensor([[[ 1.4792e-09,  4.5803e-41],
         [ 1.6314e+25,  3.0665e-41],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 1.6099e+25,  3.0665e-41],
         [ 0.0000e+00,  0.0000e+00],
         [ 1.6607e+25,  3.0665e-41],
         [ 1.6607e+25,  3.0665e-41]],

        [[ 1.6607e+25,  3.0665e-41],
         [ 0.0000e+00,  0.0000e+00],
         [ 4.7504e-43,  4.4842e-44],
         [ 1.4013e-45,  4.5801e-41],
         [-1.3535e+36,  4.5801e-41]],

        [[ 4.7784e-43,  1.8217e-44],
         [ 1.6607e+25,  3.0665e-41],
         [ 1.6607e+25,  3.0665e-41],
         [ 1.6607e+25,  3.0665e-41],
         [ 1.4013e-45,  0.0000e+00]]])

In [10]:
# Construir tensores con numeros aleatorios
x = torch.rand(3,2,3)
x

tensor([[[0.8278, 0.4829, 0.0160],
         [0.4855, 0.2508, 0.1528]],

        [[0.4092, 0.9692, 0.4110],
         [0.7829, 0.7305, 0.1603]],

        [[0.4413, 0.3921, 0.9968],
         [0.1063, 0.4249, 0.5303]]])

In [11]:
# Contruir tensor con listas
x = torch.tensor([
    [1,2,3],
    [4,2,6],
    [6,3,6]
])
x

tensor([[1, 2, 3],
        [4, 2, 6],
        [6, 3, 6]])

In [12]:
# Crear tensor con tipo definido
x = torch.tensor([1,2,4], dtype=torch.int32)
x

tensor([1, 2, 4], dtype=torch.int32)

## Operaciones

In [15]:
# ver tamano del tensor
x = torch.rand(3,4,2)
y = torch.rand(3,4,2)

# Suma
x + y

tensor([[[0.9729, 1.5551],
         [1.4092, 1.1962],
         [1.0450, 0.9312],
         [0.7746, 0.5250]],

        [[0.8936, 0.6468],
         [0.9916, 1.1348],
         [1.6542, 1.5532],
         [0.6421, 1.0463]],

        [[0.7868, 0.9315],
         [1.4575, 1.5500],
         [0.7375, 0.6934],
         [1.5392, 0.6460]]])

In [16]:
# Sumar
x.add_(y)
x

tensor([[[0.9729, 1.5551],
         [1.4092, 1.1962],
         [1.0450, 0.9312],
         [0.7746, 0.5250]],

        [[0.8936, 0.6468],
         [0.9916, 1.1348],
         [1.6542, 1.5532],
         [0.6421, 1.0463]],

        [[0.7868, 0.9315],
         [1.4575, 1.5500],
         [0.7375, 0.6934],
         [1.5392, 0.6460]]])