# Pytorch primeros pasos

In [15]:
import torch

torch.__version__

'1.7.1'

In [2]:
# Construir un tensor con valores en 0
x = torch.empty(4, 5, 2)
x

tensor([[[1.0469e-38, 9.5510e-39],
         [9.9184e-39, 9.0000e-39],
         [1.0561e-38, 1.0653e-38],
         [4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39]],

        [[1.0561e-38, 1.0653e-38],
         [1.0469e-38, 9.5510e-39],
         [1.0378e-38, 8.9082e-39],
         [1.0653e-38, 1.1204e-38],
         [1.0653e-38, 1.0194e-38]],

        [[8.4490e-39, 8.7245e-39],
         [1.1112e-38, 8.9082e-39],
         [9.5510e-39, 8.7245e-39],
         [8.4490e-39, 1.0745e-38],
         [1.0102e-38, 9.6429e-39]],

        [[9.2756e-39, 9.3674e-39],
         [4.2246e-39, 1.0286e-38],
         [1.0653e-38, 1.0194e-38],
         [4.1328e-39, 5.0510e-39],
         [1.0286e-38, 9.0919e-39]]])

In [3]:
# Construir tensores con numeros aleatorios
x = torch.rand(3,2,3)
x

tensor([[[0.4190, 0.1759, 0.9346],
         [0.4368, 0.3227, 0.3202]],

        [[0.1636, 0.2995, 0.6548],
         [0.3857, 0.9958, 0.7062]],

        [[0.2606, 0.6068, 0.4569],
         [0.9966, 0.2435, 0.5268]]])

In [4]:
# Contruir tensor con listas
x = torch.tensor([
    [1,2,3],
    [4,2,6],
    [6,3,6]
])
x

tensor([[1, 2, 3],
        [4, 2, 6],
        [6, 3, 6]])

In [23]:
# Crear tensor con tipo definido
x = torch.tensor([1,2,4], dtype=torch.int32)
x

tensor([1, 2, 4], dtype=torch.int32)

In [25]:
# ver tamano de un tensor
x = torch.rand(2,4,5)
x.size()

torch.Size([2, 4, 5])

## Operaciones

In [6]:
# ver tamano del tensor
x = torch.rand(3,4,2)
y = torch.rand(3,4,2)

# Suma
x + y

tensor([[[0.8463, 1.0121],
         [0.9668, 0.6806],
         [0.7018, 0.5523],
         [0.2661, 0.7779]],

        [[1.3902, 0.5967],
         [0.9575, 1.6580],
         [1.7309, 1.1151],
         [0.6191, 0.8245]],

        [[0.5121, 0.9653],
         [0.9935, 1.4874],
         [0.9505, 1.5872],
         [0.9491, 0.8776]]])

In [7]:
# Sumar
x.add_(y)
x

tensor([[[0.8463, 1.0121],
         [0.9668, 0.6806],
         [0.7018, 0.5523],
         [0.2661, 0.7779]],

        [[1.3902, 0.5967],
         [0.9575, 1.6580],
         [1.7309, 1.1151],
         [0.6191, 0.8245]],

        [[0.5121, 0.9653],
         [0.9935, 1.4874],
         [0.9505, 1.5872],
         [0.9491, 0.8776]]])

## Usar GPU

In [9]:
# Hay que verificar si la GPU esta disponible
torch.cuda.is_available()

True

In [10]:
torch.cuda.current_device()

0

In [21]:
torch.cuda.memory_allocated()

512

In [16]:
# Crear un tensor en la cpu
x = torch.FloatTensor([1,2,3,4])
x

tensor([1., 2., 3., 4.])

In [17]:
x.device

device(type='cpu')

In [18]:
# Crear tensor en la gpu
x = torch.FloatTensor([1,2,3,4]).cuda()
x

tensor([1., 2., 3., 4.], device='cuda:0')

In [20]:
x.device

device(type='cuda', index=0)

## NumPy Bridge

In [31]:
# convertir torch tensor a numpy array
a = torch.ones(2,3)
b = a.numpy()

print(type(a))
print(a)

print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# El torch tensor y el numpy array estan relacionados
# Si uno cambia el otro tambien
a.add_(torch.ones(2, 3))

print(a)
print(b)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]]


In [33]:
# convertir numpy array a torch tensor
import numpy as np

a = np.ones(6)
b = torch.from_numpy(a)

print(type(a))
print(a)

print(type(b))
print(b)

<class 'numpy.ndarray'>
[1. 1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
# El numpy array y El torch tensor estan relacionados
# Si uno cambia el otro tambien

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)
