# Autograd

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
y

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [3]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [5]:
out.backward()

In [6]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])